// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: proto/msg.proto

package jhaoproto

import (
	"reflect"
	"sync"
	"unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorCodeWs int32

const (
	ErrorCodeWs_Suc                   ErrorCodeWs = 0  //正确
	ErrorCodeWs_Fail                  ErrorCodeWs = 1  //错误
	ErrorCodeWs_Db_Error              ErrorCodeWs = 2  //数据库错误
	ErrorCodeWs_RegisterError_HadUser ErrorCodeWs = 3  //注册失败已存在改用户
	ErrorCodeWs_Error_Param           ErrorCodeWs = 4  //参数错误
	ErrorCodeWs_LoginError_NoUser     ErrorCodeWs = 5  //登录不存在改用户
	ErrorCodeWs_LoginError_NoPass     ErrorCodeWs = 6  //登录密码错误
	ErrorCodeWs_LoginError_Forbid     ErrorCodeWs = 7  //禁止登录
	ErrorCodeWs_LoginError_MultiLogin ErrorCodeWs = 8  //异地登录
	ErrorCodeWs_LoginError_NoLogin    ErrorCodeWs = 9  //没登录就发命令
	ErrorCodeWs_LoginError_token      ErrorCodeWs = 10 //token错误
	ErrorCodeWs_Feng_jin              ErrorCodeWs = 11 // 封禁
	ErrorCodeWs_No_user_data          ErrorCodeWs = 12 //没用户数据
	ErrorCodeWs_Server_Weihu          ErrorCodeWs = 13 //服务器维护
)

// Enum value maps for ErrorCodeWs.
var (
	ErrorCodeWs_name = map[int32]string{
		0:  "Suc",
		1:  "Fail",
		2:  "Db_Error",
		3:  "RegisterError_HadUser",
		4:  "Error_Param",
		5:  "LoginError_NoUser",
		6:  "LoginError_NoPass",
		7:  "LoginError_Forbid",
		8:  "LoginError_MultiLogin",
		9:  "LoginError_NoLogin",
		10: "LoginError_token",
		11: "Feng_jin",
		12: "No_user_data",
		13: "Server_Weihu",
	}
	ErrorCodeWs_value = map[string]int32{
		"Suc":                   0,
		"Fail":                  1,
		"Db_Error":              2,
		"RegisterError_HadUser": 3,
		"Error_Param":           4,
		"LoginError_NoUser":     5,
		"LoginError_NoPass":     6,
		"LoginError_Forbid":     7,
		"LoginError_MultiLogin": 8,
		"LoginError_NoLogin":    9,
		"LoginError_token":      10,
		"Feng_jin":              11,
		"No_user_data":          12,
		"Server_Weihu":          13,
	}
)

func (x ErrorCodeWs) Enum() *ErrorCodeWs {
	p := new(ErrorCodeWs)
	*p = x
	return p
}

func (x ErrorCodeWs) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorCodeWs) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msg_proto_enumTypes[0].Descriptor()
}

func (ErrorCodeWs) Type() protoreflect.EnumType {
	return &file_proto_msg_proto_enumTypes[0]
}

func (x ErrorCodeWs) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorCodeWs.Descriptor instead.
func (ErrorCodeWs) EnumDescriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{0}
}

type CmdIndex int32

const (
	// *预设
	CmdIndex_None CmdIndex = 0
	// *心跳
	CmdIndex_Ping  CmdIndex = 1
	CmdIndex_Login CmdIndex = 2 //登录    ReqLogin RespLogin
	// *亲友圈
	CmdIndex_club_list                 CmdIndex = 1000 //俱乐部列表   req_club_list resp_club_list
	CmdIndex_club_create               CmdIndex = 1001 //俱乐部创建 req_club_create resp_club_create
	CmdIndex_club_join                 CmdIndex = 1002 //req_club_join   resp_club_join
	CmdIndex_club_apply_list           CmdIndex = 1003 //req_club_apply_list resp_club_apply_list
	CmdIndex_club_apply_handle         CmdIndex = 1004 //req_club_apply_handle resp_club_apply_handle
	CmdIndex_club_exit                 CmdIndex = 1005 //req_club_exit resp_club_exit
	CmdIndex_club_member_list          CmdIndex = 1006 //req_club_member_list resp_club_member_list
	CmdIndex_club_delete_member        CmdIndex = 1007 //req_club_delete_member resp_club_delete_member
	CmdIndex_club_member_actor         CmdIndex = 1008 //req_club_member_actor resp_club_member_actor
	CmdIndex_club_score                CmdIndex = 1009 //req_club_score resp_club_score
	CmdIndex_club_create_room_template CmdIndex = 1010 //req_club_create_room_template resp_club_create_room_template
	CmdIndex_club_delete_room_template CmdIndex = 1011
	CmdIndex_club_room                 CmdIndex = 1012 //req_club_room resp_club_room
	// 创建房间
	CmdIndex_create_room          CmdIndex = 2000 //
	CmdIndex_server_internal_None CmdIndex = 9000000
	// 服务器内部登录
	CmdIndex_server_internal_Login                     CmdIndex = 9000001
	CmdIndex_server_internal_kill_all_users            CmdIndex = 9000002
	CmdIndex_server_internal_set_server_status         CmdIndex = 9000003
	CmdIndex_server_internal_get_server_status         CmdIndex = 9000004
	CmdIndex_server_internal_update_online             CmdIndex = 9000005
	CmdIndex_server_internal_is_in_server              CmdIndex = 9000006
	CmdIndex_server_internal_is_user_online            CmdIndex = 9000007
	CmdIndex_server_internal_club_create_room_template CmdIndex = 9000008 //
	CmdIndex_server_internal_club_delete_room_template CmdIndex = 9000009 //
	CmdIndex_server_internal_createRoom                CmdIndex = 9000010 //
)

// Enum value maps for CmdIndex.
var (
	CmdIndex_name = map[int32]string{
		0:       "None",
		1:       "Ping",
		2:       "Login",
		1000:    "club_list",
		1001:    "club_create",
		1002:    "club_join",
		1003:    "club_apply_list",
		1004:    "club_apply_handle",
		1005:    "club_exit",
		1006:    "club_member_list",
		1007:    "club_delete_member",
		1008:    "club_member_actor",
		1009:    "club_score",
		1010:    "club_create_room_template",
		1011:    "club_delete_room_template",
		1012:    "club_room",
		2000:    "create_room",
		9000000: "server_internal_None",
		9000001: "server_internal_Login",
		9000002: "server_internal_kill_all_users",
		9000003: "server_internal_set_server_status",
		9000004: "server_internal_get_server_status",
		9000005: "server_internal_update_online",
		9000006: "server_internal_is_in_server",
		9000007: "server_internal_is_user_online",
		9000008: "server_internal_club_create_room_template",
		9000009: "server_internal_club_delete_room_template",
		9000010: "server_internal_createRoom",
	}
	CmdIndex_value = map[string]int32{
		"None":                              0,
		"Ping":                              1,
		"Login":                             2,
		"club_list":                         1000,
		"club_create":                       1001,
		"club_join":                         1002,
		"club_apply_list":                   1003,
		"club_apply_handle":                 1004,
		"club_exit":                         1005,
		"club_member_list":                  1006,
		"club_delete_member":                1007,
		"club_member_actor":                 1008,
		"club_score":                        1009,
		"club_create_room_template":         1010,
		"club_delete_room_template":         1011,
		"club_room":                         1012,
		"create_room":                       2000,
		"server_internal_None":              9000000,
		"server_internal_Login":             9000001,
		"server_internal_kill_all_users":    9000002,
		"server_internal_set_server_status": 9000003,
		"server_internal_get_server_status": 9000004,
		"server_internal_update_online":     9000005,
		"server_internal_is_in_server":      9000006,
		"server_internal_is_user_online":    9000007,
		"server_internal_club_create_room_template": 9000008,
		"server_internal_club_delete_room_template": 9000009,
		"server_internal_createRoom":                9000010,
	}
)

func (x CmdIndex) Enum() *CmdIndex {
	p := new(CmdIndex)
	*p = x
	return p
}

func (x CmdIndex) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CmdIndex) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_msg_proto_enumTypes[1].Descriptor()
}

func (CmdIndex) Type() protoreflect.EnumType {
	return &file_proto_msg_proto_enumTypes[1]
}

func (x CmdIndex) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CmdIndex.Descriptor instead.
func (CmdIndex) EnumDescriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{1}
}

// *
// 传输到服务器的公共数据
// cmd_order = 命令序列号
// cmd_index = 命令编号
// time_upload = 上行时间戳(毫秒)
// time_download = 下行时间戳(毫秒)
// data = 业务逻辑data
type BaseMsg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CmdOrder      int32                  `protobuf:"varint,1,opt,name=cmdOrder,proto3" json:"cmdOrder,omitempty"`
	CmdIndex      int32                  `protobuf:"varint,2,opt,name=cmdIndex,proto3" json:"cmdIndex,omitempty"`
	TimeUpload    int64                  `protobuf:"varint,3,opt,name=timeUpload,proto3" json:"timeUpload,omitempty"`
	TimeDownload  int64                  `protobuf:"varint,4,opt,name=timeDownload,proto3" json:"timeDownload,omitempty"`
	ErrorCode     ErrorCodeWs            `protobuf:"varint,5,opt,name=errorCode,proto3,enum=jhaoproto.ErrorCodeWs" json:"errorCode,omitempty"`
	ErrorMsg      string                 `protobuf:"bytes,6,opt,name=errorMsg,proto3" json:"errorMsg,omitempty"`
	Data          []byte                 `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseMsg) Reset() {
	*x = BaseMsg{}
	mi := &file_proto_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseMsg) ProtoMessage() {}

func (x *BaseMsg) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseMsg.ProtoReflect.Descriptor instead.
func (*BaseMsg) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{0}
}

func (x *BaseMsg) GetCmdOrder() int32 {
	if x != nil {
		return x.CmdOrder
	}
	return 0
}

func (x *BaseMsg) GetCmdIndex() int32 {
	if x != nil {
		return x.CmdIndex
	}
	return 0
}

func (x *BaseMsg) GetTimeUpload() int64 {
	if x != nil {
		return x.TimeUpload
	}
	return 0
}

func (x *BaseMsg) GetTimeDownload() int64 {
	if x != nil {
		return x.TimeDownload
	}
	return 0
}

func (x *BaseMsg) GetErrorCode() ErrorCodeWs {
	if x != nil {
		return x.ErrorCode
	}
	return ErrorCodeWs_Suc
}

func (x *BaseMsg) GetErrorMsg() string {
	if x != nil {
		return x.ErrorMsg
	}
	return ""
}

func (x *BaseMsg) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ReqPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"` //版本号
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqPing) Reset() {
	*x = ReqPing{}
	mi := &file_proto_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqPing) ProtoMessage() {}

func (x *ReqPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqPing.ProtoReflect.Descriptor instead.
func (*ReqPing) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{1}
}

func (x *ReqPing) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type RespPing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	T             int64                  `protobuf:"varint,1,opt,name=t,proto3" json:"t,omitempty"` //时间戳
	N             bool                   `protobuf:"varint,2,opt,name=n,proto3" json:"n,omitempty"` //是否需要热更新
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespPing) Reset() {
	*x = RespPing{}
	mi := &file_proto_msg_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespPing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespPing) ProtoMessage() {}

func (x *RespPing) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespPing.ProtoReflect.Descriptor instead.
func (*RespPing) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{2}
}

func (x *RespPing) GetT() int64 {
	if x != nil {
		return x.T
	}
	return 0
}

func (x *RespPing) GetN() bool {
	if x != nil {
		return x.N
	}
	return false
}

// 登录
type ReqLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Account       string                 `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`       //账号
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`           //
	Nickname      string                 `protobuf:"bytes,3,opt,name=nickname,proto3" json:"nickname,omitempty"`     //呢称
	Sex           int32                  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`              //性别
	Headimgurl    string                 `protobuf:"bytes,5,opt,name=headimgurl,proto3" json:"headimgurl,omitempty"` //头像
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReqLogin) Reset() {
	*x = ReqLogin{}
	mi := &file_proto_msg_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReqLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReqLogin) ProtoMessage() {}

func (x *ReqLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReqLogin.ProtoReflect.Descriptor instead.
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{3}
}

func (x *ReqLogin) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *ReqLogin) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ReqLogin) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ReqLogin) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *ReqLogin) GetHeadimgurl() string {
	if x != nil {
		return x.Headimgurl
	}
	return ""
}

type RespLogin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserInfo      *UserInfo              `protobuf:"bytes,1,opt,name=userInfo,proto3" json:"userInfo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RespLogin) Reset() {
	*x = RespLogin{}
	mi := &file_proto_msg_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RespLogin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RespLogin) ProtoMessage() {}

func (x *RespLogin) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RespLogin.ProtoReflect.Descriptor instead.
func (*RespLogin) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{4}
}

func (x *RespLogin) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

type UserInfo struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// *服务器userid
	UserId int64 `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	// *user name
	UserName string `protobuf:"bytes,2,opt,name=userName,proto3" json:"userName,omitempty"`
	// *user photo
	UserPhoto     string `protobuf:"bytes,3,opt,name=userPhoto,proto3" json:"userPhoto,omitempty"`
	Sex           int32  `protobuf:"varint,4,opt,name=sex,proto3" json:"sex,omitempty"`
	Coins         int64  `protobuf:"varint,5,opt,name=coins,proto3" json:"coins,omitempty"`                 //金币
	Diamond       int64  `protobuf:"varint,6,opt,name=diamond,proto3" json:"diamond,omitempty"`             //钻石
	RoomId        int32  `protobuf:"varint,7,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"` //房间Id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	mi := &file_proto_msg_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_msg_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_proto_msg_proto_rawDescGZIP(), []int{5}
}

func (x *UserInfo) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserInfo) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *UserInfo) GetUserPhoto() string {
	if x != nil {
		return x.UserPhoto
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *UserInfo) GetCoins() int64 {
	if x != nil {
		return x.Coins
	}
	return 0
}

func (x *UserInfo) GetDiamond() int64 {
	if x != nil {
		return x.Diamond
	}
	return 0
}

func (x *UserInfo) GetRoomId() int32 {
	if x != nil {
		return x.RoomId
	}
	return 0
}

var File_proto_msg_proto protoreflect.FileDescriptor

const file_proto_msg_proto_rawDesc = "" +
	"\n" +
	"\x0fproto/msg.proto\x12\tjhaoproto\"\xeb\x01\n" +
	"\aBaseMsg\x12\x1a\n" +
	"\bcmdOrder\x18\x01 \x01(\x05R\bcmdOrder\x12\x1a\n" +
	"\bcmdIndex\x18\x02 \x01(\x05R\bcmdIndex\x12\x1e\n" +
	"\n" +
	"timeUpload\x18\x03 \x01(\x03R\n" +
	"timeUpload\x12\"\n" +
	"\ftimeDownload\x18\x04 \x01(\x03R\ftimeDownload\x124\n" +
	"\terrorCode\x18\x05 \x01(\x0e2\x16.jhaoproto.ErrorCodeWsR\terrorCode\x12\x1a\n" +
	"\berrorMsg\x18\x06 \x01(\tR\berrorMsg\x12\x12\n" +
	"\x04data\x18\a \x01(\fR\x04data\"#\n" +
	"\aReqPing\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"&\n" +
	"\bRespPing\x12\f\n" +
	"\x01t\x18\x01 \x01(\x03R\x01t\x12\f\n" +
	"\x01n\x18\x02 \x01(\bR\x01n\"\x88\x01\n" +
	"\bReqLogin\x12\x18\n" +
	"\aaccount\x18\x01 \x01(\tR\aaccount\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1a\n" +
	"\bnickname\x18\x03 \x01(\tR\bnickname\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x05R\x03sex\x12\x1e\n" +
	"\n" +
	"headimgurl\x18\x05 \x01(\tR\n" +
	"headimgurl\"<\n" +
	"\tRespLogin\x12/\n" +
	"\buserInfo\x18\x01 \x01(\v2\x13.jhaoproto.UserInfoR\buserInfo\"\xb7\x01\n" +
	"\bUserInfo\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1a\n" +
	"\buserName\x18\x02 \x01(\tR\buserName\x12\x1c\n" +
	"\tuserPhoto\x18\x03 \x01(\tR\tuserPhoto\x12\x10\n" +
	"\x03sex\x18\x04 \x01(\x05R\x03sex\x12\x14\n" +
	"\x05coins\x18\x05 \x01(\x03R\x05coins\x12\x18\n" +
	"\adiamond\x18\x06 \x01(\x03R\adiamond\x12\x17\n" +
	"\aroom_id\x18\a \x01(\x05R\x06roomId*\x9a\x02\n" +
	"\vErrorCodeWs\x12\a\n" +
	"\x03Suc\x10\x00\x12\b\n" +
	"\x04Fail\x10\x01\x12\f\n" +
	"\bDb_Error\x10\x02\x12\x19\n" +
	"\x15RegisterError_HadUser\x10\x03\x12\x0f\n" +
	"\vError_Param\x10\x04\x12\x15\n" +
	"\x11LoginError_NoUser\x10\x05\x12\x15\n" +
	"\x11LoginError_NoPass\x10\x06\x12\x15\n" +
	"\x11LoginError_Forbid\x10\a\x12\x19\n" +
	"\x15LoginError_MultiLogin\x10\b\x12\x16\n" +
	"\x12LoginError_NoLogin\x10\t\x12\x14\n" +
	"\x10LoginError_token\x10\n" +
	"\x12\f\n" +
	"\bFeng_jin\x10\v\x12\x10\n" +
	"\fNo_user_data\x10\f\x12\x10\n" +
	"\fServer_Weihu\x10\r*\x83\x06\n" +
	"\bCmdIndex\x12\b\n" +
	"\x04None\x10\x00\x12\b\n" +
	"\x04Ping\x10\x01\x12\t\n" +
	"\x05Login\x10\x02\x12\x0e\n" +
	"\tclub_list\x10\xe8\a\x12\x10\n" +
	"\vclub_create\x10\xe9\a\x12\x0e\n" +
	"\tclub_join\x10\xea\a\x12\x14\n" +
	"\x0fclub_apply_list\x10\xeb\a\x12\x16\n" +
	"\x11club_apply_handle\x10\xec\a\x12\x0e\n" +
	"\tclub_exit\x10\xed\a\x12\x15\n" +
	"\x10club_member_list\x10\xee\a\x12\x17\n" +
	"\x12club_delete_member\x10\xef\a\x12\x16\n" +
	"\x11club_member_actor\x10\xf0\a\x12\x0f\n" +
	"\n" +
	"club_score\x10\xf1\a\x12\x1e\n" +
	"\x19club_create_room_template\x10\xf2\a\x12\x1e\n" +
	"\x19club_delete_room_template\x10\xf3\a\x12\x0e\n" +
	"\tclub_room\x10\xf4\a\x12\x10\n" +
	"\vcreate_room\x10\xd0\x0f\x12\x1b\n" +
	"\x14server_internal_None\x10\xc0\xa8\xa5\x04\x12\x1c\n" +
	"\x15server_internal_Login\x10\xc1\xa8\xa5\x04\x12%\n" +
	"\x1eserver_internal_kill_all_users\x10¨\xa5\x04\x12(\n" +
	"!server_internal_set_server_status\x10è\xa5\x04\x12(\n" +
	"!server_internal_get_server_status\x10Ĩ\xa5\x04\x12$\n" +
	"\x1dserver_internal_update_online\x10Ũ\xa5\x04\x12#\n" +
	"\x1cserver_internal_is_in_server\x10ƨ\xa5\x04\x12%\n" +
	"\x1eserver_internal_is_user_online\x10Ǩ\xa5\x04\x120\n" +
	")server_internal_club_create_room_template\x10Ȩ\xa5\x04\x120\n" +
	")server_internal_club_delete_room_template\x10ɨ\xa5\x04\x12!\n" +
	"\x1aserver_internal_createRoom\x10ʨ\xa5\x04B\x0eZ\fgo/jhaoprotob\x06proto3"

var (
	file_proto_msg_proto_rawDescOnce sync.Once
	file_proto_msg_proto_rawDescData []byte
)

func file_proto_msg_proto_rawDescGZIP() []byte {
	file_proto_msg_proto_rawDescOnce.Do(func() {
		file_proto_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_msg_proto_rawDesc), len(file_proto_msg_proto_rawDesc)))
	})
	return file_proto_msg_proto_rawDescData
}

var file_proto_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_msg_proto_goTypes = []any{
	(ErrorCodeWs)(0),  // 0: jhaoproto.ErrorCodeWs
	(CmdIndex)(0),     // 1: jhaoproto.CmdIndex
	(*BaseMsg)(nil),   // 2: jhaoproto.BaseMsg
	(*ReqPing)(nil),   // 3: jhaoproto.ReqPing
	(*RespPing)(nil),  // 4: jhaoproto.RespPing
	(*ReqLogin)(nil),  // 5: jhaoproto.ReqLogin
	(*RespLogin)(nil), // 6: jhaoproto.RespLogin
	(*UserInfo)(nil),  // 7: jhaoproto.UserInfo
}
var file_proto_msg_proto_depIdxs = []int32{
	0, // 0: jhaoproto.BaseMsg.errorCode:type_name -> jhaoproto.ErrorCodeWs
	7, // 1: jhaoproto.RespLogin.userInfo:type_name -> jhaoproto.UserInfo
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_msg_proto_init() }
func file_proto_msg_proto_init() {
	if File_proto_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_msg_proto_rawDesc), len(file_proto_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_msg_proto_goTypes,
		DependencyIndexes: file_proto_msg_proto_depIdxs,
		EnumInfos:         file_proto_msg_proto_enumTypes,
		MessageInfos:      file_proto_msg_proto_msgTypes,
	}.Build()
	File_proto_msg_proto = out.File
	file_proto_msg_proto_goTypes = nil
	file_proto_msg_proto_depIdxs = nil
}
